# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "48e1a35b27ca5f9c5982f61e4e292384"
name = "shippingfunctionextension"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_customers,read_customer_zip_code"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
